# yaml-language-server: $schema=../crates/graphql-config/schema/graphqlrc.schema.json
projects:
  pokemon:
    schema: pokemon/schema.graphql
    documents: "pokemon/src/**/*.{graphql,gql,ts,tsx,js,jsx}"
    lint: recommended

  starwars:
    schema: starwars/schema.graphql
    documents: "starwars/src/**/*.{graphql,gql,ts,tsx,js,jsx}"
    lint: recommended
