# GraphQL LSP Project Configuration
# yaml-language-server: $schema=crates/graphql-config/schema/graphqlrc.schema.json
projects:
  pokemon:
    schema: test-workspace/pokemon/schema.graphql
    documents: "test-workspace/pokemon/src/**/*.{graphql,gql,ts,tsx,js,jsx}"
    lint: recommended

  starwars:
    schema: test-workspace/starwars/schema.graphql
    documents: "test-workspace/starwars/src/**/*.{graphql,gql,ts,tsx,js,jsx}"
    lint: recommended

  github:
    schema: "test-workspace/github/schema/*.graphql"
    documents:
      - "test-workspace/github/src/**/*.graphql"
      - "test-workspace/github/src/**/*.ts"
      - "test-workspace/github/src/**/*.tsx"
    lint:
      extends: recommended
      rules:
        no_deprecated: warn
        require_id_field: [warn, { fields: ["id", "databaseId"] }]

  github-admin:
    schema:
      - "test-workspace/github/schema/*.graphql"
      - "test-workspace/github/admin/schema/*.graphql"
    documents: "test-workspace/github/admin/src/**/*.graphql"
    lint:
      extends: recommended
      rules:
        no_deprecated: error
        require_id_field:
          severity: error
          options:
            fields: ["id"]

  countries:
    schema:
      url: https://countries.trevorblades.com/graphql
    documents: "test-workspace/countries/src/**/*.{graphql,ts}"
    lint: recommended
