# GraphQL LSP Project Configuration
# yaml-language-server: $schema=crates/graphql-config/schema/graphqlrc.schema.json
projects:
  pokemon:
    schema: test-workspace/pokemon/schema.graphql
    documents: "test-workspace/pokemon/src/**/*.{graphql,gql,ts,tsx,js,jsx}"
    extensions:
      lint:
        extends: recommended
        rules:
          uniqueNames: error
          requireIdField: warn

  starwars:
    schema: test-workspace/starwars/schema.graphql
    documents: "test-workspace/starwars/src/**/*.{graphql,gql,ts,tsx,js,jsx}"
    extensions:
      lint:
        extends: recommended
        rules:
          uniqueNames: error
          requireIdField: warn

  github:
    schema:
      - "test-workspace/github/schema/*.graphql"
      - "test-workspace/github/schema/*.ts"
    documents:
      - "test-workspace/github/src/**/*.graphql"
      - "test-workspace/github/src/**/*.ts"
      - "test-workspace/github/src/**/*.tsx"
    extensions:
      lint:
        extends: recommended
        rules:
          uniqueNames: error
          noDeprecated: warn
          requireIdField: [warn, { fields: ["id", "databaseId"] }]

  github-admin:
    schema: "test-workspace/github/admin/schema/*.graphql"
    documents: "test-workspace/github/admin/src/**/*.graphql"
    extensions:
      lint:
        extends: recommended
        rules:
          uniqueNames: error
          noDeprecated: error
          requireIdField:
            severity: error
            options:
              fields: ["id"]

  countries:
    schema:
      url: https://countries.trevorblades.com/graphql
      timeout: 30
      retry: 2
    documents: "test-workspace/countries/src/**/*.{graphql,ts}"
    extensions:
      lint:
        extends: recommended
        rules:
          uniqueNames: error
          requireIdField: warn

  lint-examples:
    schema: "test-workspace/lint-examples/schema/**/*.graphql"
    documents: "test-workspace/lint-examples/src/**/*.graphql"
    extensions:
      lint:
        rules:
          # Document rules
          noAnonymousOperations: warn
          operationNameSuffix: warn
          redundantFields: warn
          unusedVariables: warn
          noDuplicateFields: warn
          selectionSetDepth: [warn, { maxDepth: 3 }]
          namingConvention: warn
          alphabetize: [warn, { selections: true, arguments: true, variables: true }]
          loneExecutableDefinition: warn
          # Document + schema rules
          noDeprecated: warn
          requireIdField: warn
          # Project rules
          uniqueNames: warn
          unusedFields: warn
          unusedFragments: warn
          noOnePlaceFragments: warn
          # Schema rules
          requireDescription: warn
          requireDeprecationReason: warn
          noHashtagDescription: warn
          strictIdInTypes: warn
          noTypenamePrefix: warn
          inputName: warn
          descriptionStyle: warn
          noUnreachableTypes: warn
          uniqueEnumValueNames: warn
          noScalarResultTypeOnMutation: warn
          requireFieldOfTypeQueryInMutationResult: warn
