# GraphQL LSP Project Configuration
projects:
  pokemon:
    schema: test-workspace/pokemon/schema.graphql
    documents: "test-workspace/pokemon/src/**/*.{graphql,gql,ts,tsx,js,jsx}"
    extensions:
      lint:
        extends: recommended
        rules:
          uniqueNames: error
          requireIdField: warn

  starwars:
    schema: "test-workspace/starwars/schema.graphql"
    documents: "test-workspace/starwars/src/**/*.{graphql,gql,ts,tsx,js,jsx}"
    extensions:
      lint:
        extends: recommended
        rules:
          uniqueNames: error
          requireIdField: warn

  github:
    schema:
      - "test-workspace/github/schema/*.graphql"
      - "test-workspace/github/schema/*.ts"
    documents:
      - "test-workspace/github/src/**/*.graphql"
      - "test-workspace/github/src/**/*.ts"
      - "test-workspace/github/src/**/*.tsx"
    extensions:
      lint:
        extends: recommended
        rules:
          uniqueNames: error
          noDeprecated: warn
          requireIdField: [warn, { fields: ["id", "databaseId"] }]

  github-admin:
    schema: "test-workspace/github/admin/schema/*.graphql"
    documents: "test-workspace/github/admin/src/**/*.graphql"
    extensions:
      lint:
        extends: recommended
        rules:
          uniqueNames: error
          noDeprecated: error
          requireIdField:
            severity: error
            options:
              fields: ["id"]

  countries:
    schema:
      url: https://countries.trevorblades.com/graphql
      timeout: 30
      retry: 2
    documents: "test-workspace/countries/src/**/*.{graphql,ts}"
    extensions:
      lint:
        extends: recommended
        rules:
          uniqueNames: error
          requireIdField: warn

  misconfigured-schema:
    # expect 2 errors: schema file does not exist, and documents file does not exist
    schema: "test-workspace/misconfigured-schema/schema.graphql"
    documents: "test-workspace/misconfigured-schema/query.graphql"

  misconfigured-documents:
    # expect 2 errors: schema file does not exist, and documents file does not exist
    schema: "test-workspace/misconfigured-documents/schema.graphql"
    documents: "test-workspace/misconfigured-documents/query.graphql"
